### ISSUE TITLE
VideoDevice returned image frames can contain mostly empty data

### ISSUE THREAD

**Issue by CodedBeard** [dotnet/iot#1689] opened 2021-10-13 14:58 UTC
**Describe the bug**

While investigating the image color accuracy issue described in #1688, I noticed that my network was starting to have performance issues the more video devices i had running. At the time i was testing a Raspberry Pi 4 8GB running arm64 raspberry os with a low resolution night vision camera. I realised that most of the traffic from the camera arriving at my browser, was the image (around 25kb) followed by megabytes of 0's.

After digging in further, I identified the issue is being caused by the code that process the captured frames, [using the buffer size instead of the size of the image within the buffer](https://github.com/dotnet/iot/blob/facfd52195915d9e10640c6ce6721ef1c17ffdd3/src/devices/Media/VideoDevice/Devices/UnixVideoDevice.cs#L317). In my earlier testing with a different combination of camera/pi, this was not obvious as the images were of a similar size to the buffers, but with this low resolution camera, the issue became stark due to how much larger the resulting frames were compared to what they should have been.

From what I can tell, the size of the buffer changes dependent on the device being used, so using a high ram pi with a low res camera results in 99% of the buffer being empty. I've not confirmed this is the case, but certainly appears to correlate with my testing.

[In my fork](https://github.com/CodedBeard/iot/commit/bc5558e68847ec1bbb790d73a728001a40c6c2b2), I've 'fixed' this issue using the `MemoryExtensions.TrimEnd(ReadOnlySpan<byte>)` method to get the actual length of the data within the buffer to be returned, but that method is not available in netcoreapp2.1, so wasn't sure that would be an acceptable fix for PR back.

**Steps to reproduce**

This can be reproduced using the MJPEG sample project in the repo, though it does need a device with a high memory to image size ratio to be obvious.

**Expected behavior**

The returned frame contains minimal additional space beyond the image data, only accounting for if `ArrayPool` is in use to reduce allocations (as the rented byte[] will always be larger than required)

**Actual behavior**

In some circumstances, the returned frame is 99.9% empty data

**Versions used**

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /home/pi/dotnet/sdk/6.0.100-rc.1.21458.32/

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  6.0.100-rc.1.21458.32 [/home/pi/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/home/pi/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/home/pi/dotnet/shared/Microsoft.NETCore.App]
```
- Version of `System.Device.Gpio`: built from main
- Version of `Iot.Device.Bindings` built from main

**Comment by CodedBeard** [comment] 2022-06-09 21:00
@joperezr Is there something specifically you need feedback on? While I've not had a chance to look at this recently due to family/work, as far as I can see, the frame is still being created with the buffer length, not the size of the image itself.

**Comment by joperezr** [comment] 2022-06-09 21:11
Sorry that we missed that @CodedBeard, we recently recycled some of our labels and added some issue management automation which is probably why we missed your update and the bot commented to notify there wasn't enough info here.

@raffaeler or @Ellerbach does anyone of you have the device that @CodedBeard pointed out above (the NOIR night vision camera) so we can test if the issue repros for us as well?

**Comment by raffaeler** [comment] 2022-06-10 15:10
I should have one but it's in use. Anyway I should also be able to stop the pi next week and make the test.
I'll let you know asap.

**Comment by raffaeler** [comment] 2022-06-13 15:22
The bad news is that I do not have a NOIR available as I believed.
On the other side I could repro the issues that I documented [here](https://github.com/dotnet/iot/issues/1799#issuecomment-1154057026) with 4 different types of cameras I tested.

**Comment by raffaeler** [comment] 2022-07-01 06:26
I am closing this in favor of https://github.com/dotnet/iot/issues/1799 since it has the same root cause.
If you feel that instead they don't share the same cause, please feel free to reopen this.

**Closed by raffaeler** 2022-07-01 06:26 UTC
Labels: bug
