### ISSUE TITLE
Add support for 2/3 color e-ink displays

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/iot#234] opened 2019-02-14 23:59 UTC
Many of displays are driven by ICs from ILI Technology, such as those from Waveshare and Good Display.

I have a display from Waveshare that is driven by the IL0376F. I'm writing a hopefully generic base driver that can be used to implement the following chips:

IL0326, IL0371, IL0373, IL0376, IL0389 (and others?)

I haven't done an exhaustive search, if anyone else has links to other chips in this series they would be welcome.

**Comment by krwq** [comment] 2019-02-21 07:44
I've just ordered ILI9341 - not sure if this is the same family - not an e-Ink but the interface might be similar/same - this particular is called TFT LCD display module.

One thing I'm not sure about the stuff from ILI that every page on the datasheet says - actually not sure if I can even copy it - see footer on most of the pages of i.e.:
https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf

this kinda suggest that you can't write code using this spec? technically speaking creating enum with values from such datasheet would be reproducing information there. Not sure if I misunderstand that but would be nice if someone looked at that

**Comment by krwq** [comment] 2022-04-28 16:53
[Triage] It's nice to have issue but considering more than 3 years have passed since this was created and no one requested it closing the issue. We're welcome to take any contributions but we don't need an issue lying around

**Closed by krwq** 2022-04-28 16:53 UTC
Labels: enhancement, area-device-bindings
