### ISSUE TITLE
Disposing pins is not always expected

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#347] opened 2019-03-27 01:11 UTC
I think we should have a way of telling controller that we don't want any cleanup to happen for the specific pin (in my case `reset` pin)

Here is the scenario I've encountered recently:
I've worked on oLED bindings - one of the oLED pins is `reset`.
Scenario is following:
- start .NET app to draw something and close it

Here is what happens instead:
- .NET app starts, draws whatever user requested
- Dispose is called
- Reset PIN is set to Low
- oLED is reset
- .NET app finishes
- oLED is black

current solution for this problem was not to call Dispose at all (uses the fact that .NET Core doesn't call dispose on cleanup).

**Comment by joperezr** [comment] 2019-04-10 21:35
Interesting scenario. I kind of feel that if we wanted to do this we might leak some files for specific set of drivers. For example, the SysFS driver would need to leave some files behind in order to persist the value. I'm not 100% sure  on this, but I believe that is the case.

**Comment by shaggygi** [comment] 2019-06-19 21:43
While I'm just speculating with the work on `I2cController`, we could eventual evolve the IGpioController to manage GpioPins (or IGpioPins) instead.  This way, you could possibly have a `ShouldDispose` property like we might be adding to `I2cDevice`.

**Comment by joperezr** [comment] 2019-07-09 22:59
I don't think we want to optimize for the scenario you specified above with the OLED displays. As for the disposing pattern, we have that covered in another issue so I will close this as a dupe as the fix will be tracked by that other one

**Comment by joperezr** [comment] 2019-07-09 22:59
duplicate of #419

**Closed by joperezr** 2019-07-09 22:59 UTC
Labels: Design Discussion, area-System.Device.Gpio, enhancement, up-for-grabs
