### ISSUE TITLE
[Proposal] I2cController and II2cController

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#118] opened 2018-12-24 18:54 UTC
Similar to the ```GpioController```, there needs to be a mechanism to determine the best ```I2cDevice``` to use.

#### Updated 6/18/2019

`I2cDevice` allows for an easy way to create an I2C connection between a master controller and one device binding.  However, there are scenarios where a new type of **controller** can manage related devices more efficiently.

# Rationale and Usage

**System.Device.Gpio Consistency** - Other APIs provide controllers that work with low-level drivers to perform the functional operations.  For example, `GpioController` informs related driver to write logic-levels to pins and `PwmController` informs related driver to write variable frequency to pins.  The `I2cController` will inform which I2C device to read/write data.

**Multiple Device Management** - Other controllers also can open and close multiple pins that will be controlled.  Sometimes hardware configurations require a master to communicate with multiple devices on the same I2C bus.  This is a current limitation with `I2cDevice` as it requires the bus ID & device address when instantiating and the read/write methods communicate with only the one device.

**Default OS Implementation** - Most current device binding samples specifically define the `I2cDevice` related to executing OS (e.g. `UnixI2cDevice` or `Windows10I2cDevice`).  This forces users to update sample code when running on different hardware and OS.  This proposal will offer a method to generate the default `I2cDevice` for OS similar to how a `GpioController` provides a default `GpioDriver`.

**Controller Interface** - In addition to providing a default `I2cController`, this proposal also includes an `II2cController` as there are use-cases where bindings could be a master I2C controller that can control other I2C devices.

# Proposed Changes

## 1. Add New II2cController and I2cController

Add a new `II2cController` interface that includes the same read/write methods as an `I2cDevice` with the addition of specified bus ID and address parameters.  This allows the controller to know which device to use for communications.  There are also methods to open/close devices.

```csharp
public interface II2cController : IDisposable
{
    void OpenDevice(I2cConnectionSettings settings, bool shouldDispose = true);
    void OpenDevice(I2cDevice device, bool shouldDispose = true);
    void CloseDevice(I2cConnectionSettings settings);
    void CloseDevice(I2cDevice device);
    void ClearDevices();
    bool TryGetDevice(int busId, int address, out I2cDevice device);
    void Read(int busId, int address, Span<byte> buffer);
    byte ReadByte(int busId, int address);
    void Write(int busId, int address, ReadOnlySpan<byte> buffer);
    void WriteByte(int busId, int address, byte value);
    void WriteRead(int busId, int address, ReadOnlySpan<byte> writeBuffer, Span<byte> readBuffer);
}
```

The `I2cController` class will implement the new `II2cController` interface and be the default for most apps and device bindings.  The controller is instantiated with zero I2C devices to control.  More devices can be opened/closed similar to pins on other controllers.

```csharp
// Class
public class I2cController : II2cController

// Constructor
public I2cController()
```

The creation of devices with a new static helper method that attempts to pick the best I2C device for OS app is executing on.  This static method will be added to a new `sealed partial class` respective to OS.

```csharp
// I2cController.Linux.cs
public static I2cDevice Create(I2cConnectionSettings settings) => new UnixI2cDevice(settings);
// I2cController.Windows.cs
public static I2cDevice Create(I2cConnectionSettings settings) => new Windows10I2cDevice(settings);
```
    
### Example 1.1
Instantiate a controller and open a device.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
var i2cController = new I2cController();
i2cController.OpenDevice(settings);
```

### Example 1.2
Open a new device to controller that already contains device with specified address.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
var i2cController = new I2cController();
i2cController.OpenDevice(settings);
i2cController.OpenDevice(settings); // Throws exception because device with address already exists.
```

### Example 1.3
Open two devices with same address but on different buses.

```csharp
int busId0 = 0;
int busId1 = 1;
int address = 0x21;
var settings0 = new I2cConnectionSettings(busId0, address);
var settings1 = new I2cConnectionSettings(busId1, address);
var i2cController = new I2cController();
i2cController.OpenDevice(settings0);
i2cController.OpenDevice(settings1);
```

### Example 1.4
Open a new device that implements `I2cDevice` to controller.

**NOTE**: This I2C software implementation doesn't currently exist but is the same concept as the SPI software implementation.  See [[Proposal] Provide a Software implementation of the SPI protocol](https://github.com/dotnet/iot/issues/122) for related details.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
int sdaPin = 17;
int sclPin = 18;
var gpioController = new GpioController();

var i2cDevice = new GpioI2cDevice(
    settings,
    sdaPin,
    sclPin,
    gpioController);

var i2cController = new I2cController();
i2cController.OpenDevice(i2cDevice);
```

### Example 1.5
Close a device from controller that doesn't contain device with specified address.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
var i2cController = new I2cController();

i2cController.OpenDevice(settings);
i2cController.CloseDevice(new I2cConnectionSettings(busId, 0x45));  // Throws exception because no device with specified address exists.
```

### Example 1.6
Reading from a specific device in controller.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
var i2cController = new I2cController();
i2cController.OpenDevice(settings);

byte value = i2cController.ReadByte(busId, address);

// Or...

Span<byte> buffer = stackalloc byte[3];
i2cController.Read(busId, address, buffer);
```

### Example 1.7
Write to a specific device in controller.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
var i2cController = new I2cController();
i2cController.OpenDevice(settings);

byte value = 0x23;
i2cController.WriteByte(busId, address, value);

// Or...

ReadOnlySpan<byte> buffer = new byte[] { 0x12, 0x23, 0x45 };
i2cController.Write(busId, address, buffer);
```

## 2. Disposing of I2cControllers and I2cDevices

- [ ] WIP: Need to review topic and create examples here.  There are some initial dispose notes below (delete after adding to this section).

**NOTE**: This dispose pattern needs to fit other controllers to not confuse others, as well.

A new `public bool ShouldDispose` property is added to `I2cDevice` class for different disposing scenarios.  This property will allow controllers/bindings to know if it should dispose device(s) if/when the controller/binding is being disposed.  By default, this property should be set to `true` as this is the intention in most cases.

```csharp
public abstract class I2cDevice : IDisposable
{
    public bool ShouldDispose { get; set; } => true;

    // other current code...
}
```

### Example 2.1
Use controller with default device (ShouldDispose = true).

### Example 2.2
Use controller with provided device (ShouldDispose = false).

## 3. Device Binding Guidance
This section points out a few areas bindings should use that use `I2cDevice`.

### Binding Constructors

Bindings that use I2C should be the owners of opening the `I2cDevice` on the controller.  Therefore, the bindings should provide at least 2 constructor overloads that offer the option of using `I2cConnectionSettings` or `I2cDevice`.  This will make it easier when instantiating the bindings with other apps and APIs.  It is assumed there will be no other I2C device with the same bus ID and address as it will throw an exception when the binding adds the device to the controller.

### Example 3.1
Instantiate a device binding with specified settings without a defined controller.

**NOTE**: The default controller would be instantiated similar to a master `IGpioController` when not defined.  Since the controller is not provided and only settings, there is no way to add a specified `I2cDevice`.  Therefore, the intent is to also create a default `I2cDevice` when it is added to controller.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
var mcp23018 = new Mcp23018(settings);  // Default controller and default device is opened within.
```

### Example 3.2
Instantiate a device binding with specified device without a defined controller.

**NOTE**: The default controller would be instantiated similar to a master `IGpioController` when not defined.  The specified device will then be opened.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
MyI2cDevice device = new MyI2cDevice(settings);  // New device that implements I2cDevice.
var mcp23018 = new Mcp23018(myI2cDevice);  // Default controller and specified device is opened within.
```

### Example 3.3
Instantiate a device binding with specified settings (or device) and specified controller.

```csharp
int busId = 1;
int address = 0x20;
var i2cController = new WhizBangI2cController();

// By settings.
var settings = new I2cConnectionSettings(busId, address);
var mcp23018 = new Mcp23018(settings, i2cController);

// Or...

// By device.
var device = I2cController.Create(new I2cConnectionSettings(busId, address));
i2cController.OpenDevice(device, i2cController);
```

### Example 3.4
Instantiate a controller for a binding that has multiple devices with fixed addresses.

See [Adding GHI Fez Cream driver](https://github.com/dotnet/iot/issues/379) for related details.

**NOTE**: This hardware is a RPi HAT with hard-wired pins on I2C bus 1.

```csharp
var ghiFezCream = new GhiFezCream(); // Adds all 4 on-board devices to binding.

// Or...

// Adds all 4 on-board devices to binding using default devices on specified controller.
var i2cController = new I2cController();
var ghiFezCream = new GhiFezCream(i2cController);

// Or...

// Adds all 4 on-board devices to binding using specified devices and specified controller.
int busId = 1;

var ghiFezCream = new GhiFezCream(
    new GpioI2cDevice(new I2cConnectionSettings(busId, GhiFezCream.Pca9535AddressIc1)),
    new GpioI2cDevice(new I2cConnectionSettings(busId, GhiFezCream.Pca9535AddressIc2)),
    new GpioI2cDevice(new I2cConnectionSettings(busId, GhiFezCream.Ads7830IpwtAddress)),
    new GpioI2cDevice(new I2cConnectionSettings(busId, GhiFezCream.Pca9685Address)),
    i2cController);

public class GhiFezCream
{
    // Constructor shows it adding fixed devices.
    public GhiFezCream(II2cController? i2cController = null)
    {
        int busId = 1;
        i2cController = i2cController ?? new I2cController();

        i2cController.OpenDevice(new I2cConnectionSettings(busId, GhiFezCream.Pca9685Address)),
        i2cController.OpenDevice(new I2cConnectionSettings(busId, GhiFezCream.Pca9535AddressIc2)),
        i2cController.OpenDevice(new I2cConnectionSettings(busId, GhiFezCream.Ads7830IpwtAddress)),
        i2cController.OpenDevice(new I2cConnectionSettings(busId, GhiFezCream.Pca9685Address)),
    }
    
    // Or you could overload with specified devices.
    public GhiFezCream(
        I2cDevice pca9535Ic1,
        I2cDevice pca9535Ic2 ,
        I2cDevice ads7830Ipwt ,
        I2cDevice pca9685 ,
        II2cController? i2cController = null)
    {
        i2cController = i2cController ?? new I2cController();
        i2cController.OpenDevice(pca9535Ic1);
        i2cController.OpenDevice(pca9535Ic2);
        i2cController.OpenDevice(ads7830Ipwt);
        i2cController.OpenDevice(pca9685);
    }

    public static int Pca9535AddressIc1 => 0x23;
    public static int Pca9535AddressIc2 => 0x25;
    public static int Ads7830IpwtAddress => 0x48;
    public static int Pca9685Address => 0x70;
}
```

### Example 3.5
Instantiate a controller, opens another I2C device on bus, and then opens a binding.

```csharp
int busId = 1;
int address = 0x21;
var settings = new I2cConnectionSettings(busId, address);
var i2cController = new I2cController();
i2cController.OpenDevice(settings);  // This opens a default device using specified settings.

var bindingSettings = new I2cConnectionSettings(busId, 0x20);
var mcp23018 = new Mcp23018(bindingSettings, i2cController);  // Specified controller opens default device within on same bus as other device.
```

### Disposing of Bindings

Bindings should implement `IDisposable` where it disposes the related devices.

```csharp
public class MyBinding : IDisposable
{
    public void Dispose()
    {
        // This will remove the device from controller and only dispose if ShouldDispose is true. 
        _i2cController.CloseDevice(_i2cSettings);
    }
}
```

# Update I2C Device Namespace

:warning: This topic is related to a future PR that will be a breaking change.

There have been discussions how we should structure/name some of the folders and classes throughout API.  I originally thought we should rename I2C devices to use 'Driver' instead to be consistent with other types.  For example, `I2cDevice` would be renamed `I2cDriver`.

My opinions have changed as the new I2C controller fits quite nicely with the current device naming.  Although, there is a breaking change needed with the folder structure and related namespace.  This could be implemented before the release of v1 in a future PR.   So this proposal is in-line to the current device class naming.  It only states we need to change the namespace later (hopefully soon after).

```csharp
// From...
namespace System.Device.I2c.Drivers
// To...
namespace System.Device.I2c.Devices
```

See [[Proposal] Move classes and rename to be consistent throughout API](https://github.com/dotnet/iot/issues/126) for related details.

# Related Issues

- [I2C APIs should take address on Read/Write](https://github.com/dotnet/iot/issues/214)
- [Adding GHI Fez Cream driver](https://github.com/dotnet/iot/issues/379)
- [[Proposal] Provide controller provider interfaces](https://github.com/dotnet/iot/issues/125)
- [[Proposal] Move classes and rename to be consistent throughout API](https://github.com/dotnet/iot/issues/126)
- [SenseHat does not create appropriate I2C devices](https://github.com/dotnet/iot/issues/498)
- [Reconsider Dispose pattern across devices](https://github.com/dotnet/iot/issues/419)

**Comment by shaggygi** [comment] 2018-12-24 19:55
To be consistent with GPIO and PWM naming structure, should the following files/classes be updated with Driver instead of Device?

```
I2c
  Driver
    UnixI2cDevice.Linux.cs -> UnixI2cDriver.Linux.cs
    UnixI2cDevice.Windows.cs -> UnixI2cDriver.Windows.cs
    Windows10I2cDevice.Linux.cs -> Windows10I2cDriver.Linux.cs
    Windows10I2cDevice.Windows.cs -> Windows10I2cDriver.Windows.cs
  I2cDevice.cs -> I2cDriver.cs
```

Therefore...
```
var connectionSettings = new I2cConnectionSettings(busId, deviceAddress);
var i2cDriver = new UnixI2cDriver(connectionSettings);
byte data = i2cDriver.ReadByte();
```

I2cDevice seems like it sticks well, but like GPIO PinNumberingScheme, I2cConnectionSettings is similar to setting up the way the I2C "driver" will work.

IMHO, just seems like Driver would be better at this point to keep consistent with the others (GPIO, PWM, etc.).

**Comment by joperezr** [comment] 2019-01-10 17:54
Agreed that we need this. The next steps are to have this issue be a formal Api proposal so that the board can review it, and approve it so that we can submit a PR.

**Comment by joperezr** [comment] 2019-01-10 17:55
We should also include an SPIController on this proposal as well, as they are related and will be very similar.

**Comment by shaggygi** [comment] 2019-05-27 01:57
@joperezr If the plan for I2C/SPI controllers is to mainly determine best device to use for platform, I still think this [older PR](https://github.com/dotnet/iot/pull/110) is still valid.  Thoughts?

**Comment by shaggygi** [comment] 2019-06-15 18:25
@joperezr Since this is labeled as 'up-for-grabs', please assign to me.  I came up with some good thoughts this week and currently working on proposal notes to add here soon.

I originally opened this issue specifically for I2C and another SPI (#119), but we later thought it could be combined.  My proposals will be big enough to justify separate reviews and implementations, so I renamed issues back for individual specifics.  Thx

**Comment by shaggygi** [comment] 2019-06-16 12:15
@joperezr @krwq Proposal was updated above.  Please review when you get a few minutes.  Thx

**Comment by shaggygi** [comment] 2019-06-16 21:55
After getting into development and the weeds for this proposal, I needed to make a slight change to include the bus ID as a way to manage devices.  This makes it one extra parameter, but believe it makes more sense while comparing to `PwmController` (chip/channel) and how the `SpiController` (bus ID/chip select line) will work.  In addition, this change makes it easier to work with a device that contains multiple buses (e.g. RPi3, [TCA9548A](https://www.digikey.com/catalog/en/partgroup/tca9548a-i-c-multiplexer/56635?utm_adgroup=Programmers%20Dev&slid=&gclid=EAIaIQobChMI7ZjHibLu4gIVho-zCh3L4AKwEAAYASAAEgKZgvD_BwE), etc.).  The proposal and WIP PR has been updated to reflect change.

**Comment by krwq** [comment] 2019-06-17 04:35
@joperezr I think we should address this as part of 3.0, especially if @shaggygi is willing to help fix this

**Comment by joperezr** [comment] 2019-06-17 18:07
In general the proposal looks great thanks a lot for working on this @shaggygi 

Here are some thoughts on the above proposal:

1. Regarding the II2cController interface members:
```c#
    void AddDevice(int busId, int address);
    void AddDevice(I2cDevice device);
    void RemoveDevice(int busId, int address);
    void ClearDevices();
```
I believe that in order to echo a bit more of what we are doing with the other controllers (Gpio and PWM) we should instead use Open and Close instead of Add and Remove, just so that it feels that the API is familiar with the rest of the library. Also, for the Open/Close methods I would only have two overloads, one that takes the I2cDevice, and one that takes the I2cConnectionSettings (meaning we should remove the one that takes busId and address).

2. Regarding the constructors on II2cController:
```c#
// Constructor overloaded
public I2cController(int busId, int address)
public I2cController(I2cConnectionSettings settings)
public I2cController(I2cDevice device)
```
I don't like these very much, as it might be a bit confusing to have I2cControllers take similar parameters to what an I2cDevice constructor would. Think of this similar to what the Collections classes in the BCL usually look like, usually you would first initialize a List for example, and then call the Add methods later, instead of passing a single member of the list to the list constructor. For this, I would just keep a parameter-less constructor, and simply call the Open/Close in order to add/remove I2cDevices. What do you think?

3. Regarding static method:
```c#
public static I2cDevice CreateDevice(I2cConnectionSettings settings)
```
I'd say that there is no big need for this one, given that the Open method that will take ConnectionSettings will effectively do this(this meaning picking the right device for the OS), so there is no big need for another static method that does the same thing.

4. Open question. I'm wondering how should we handle the case where somebody creates an I2cDevice, and then calls the OpenDevice method on a controller passing in connection settings instead of the I2cDevice instance. In this case, there would now effectively be 2 different I2c device instances, and you might find the case where one disposes the other. Speaking of which, did you give some thought into whether or not the I2cController would dispose the I2cDevices in it when calling dispose()? If so, perhaps we will want to provide an API to override this behavior if necessary like:
```c#
public class I2cController
{
  //...
  public bool ShouldDisposeDevices { get; set; }
  //...
}
```

What do you think?

**Comment by shaggygi** [comment] 2019-06-17 22:00
@joperezr Thanks for the feedback.  Here are some notes.

1. I sort of like Add/Remove better, but it is better to keep similar to the other controllers.  I updated to Open/Close.
2. I was on the fence on adding parameters to constructors, but was thinking it'd make it easy to quickly add a device while creating the controller.  We don't add pins for the GPIO/PWM controllers, so I removed to keep consistent.
3.  Thanks for explaining and pointing out the partial classes for each OS (wasn't thinking about that approach).  This makes more sense and better than the interop code.  I removed.
4. Disposing is a good point and not sure.  I know there are chats going on in other areas, so maybe this fits with those talks.  I'll try to ponder a little.

Until next time... I'm cleaning up the changes to reflect the feedback.  Should have an update on PR in a few. 👍

**Comment by shaggygi** [comment] 2019-06-17 22:18
Note to self related to disposing...

What if we used `ShouldDisposeDevices ` property as @joperezr mentioned above  where if `true`, it would dispose all opened devices when disposing the controller.

We could add a 2nd `ShouldDisposeDevice`  parameter for `CloseDevice` method.  This could be an optional parameter and defulat to `true`.  If set to false, the might want to continue use elsewhere?

Most of the time the intent is to dispose of the device(s) when disposing the controller as the app/process is probably shutting down.

**Comment by joperezr** [comment] 2019-06-18 16:52
> We could add a 2nd ShouldDisposeDevice parameter for CloseDevice method. This could be an optional parameter and defulat to true. If set to false, the might want to continue use elsewhere?

I like the idea, but the problem is that you might have the case where people will dispose the controller without closing the device. In this case, should the device be disposed? One alternative is to have that optional parameter of shouldDispose passed in when calling OpenDevice, that way you could even pick which devices in the controller would get automaticly disposed, and which ones will be preserved. What do you think?

**Comment by shaggygi** [comment] 2019-06-18 18:56
@joperezr I think we're on the same page.  I'm thinking (and beginning to document in proposal above in section 3) we could have a `ShouldDispose` for both controller and devices.  This would allow the various scenarios of when/what to dispose.  It would be more of a default value of `true` as that would be what is expected in most cases.  I like have as just a default value instead of passing `OpenDevice` method, but seems like it would work either way.

```csharp
public bool ShouldDispose { get; set; }
```

```csharp
// For controller.
// With property default to true.
var controller = new I2cController();
// Or include optional parameter for constructor.
var controller = new I2cController(bool shouldDispose = true);

// For device
// With property default to true.
controller.OpenDevice(settings);
// Or include optional parameter for constructor.
controller.OpenDevice(settings, bool shouldDispose = true);
```

Still pondering.

**Closed** 2019-06-25 22:39 UTC
Labels: api-suggestion, area-System.Device.Gpio
