### ISSUE TITLE
Orange PI 5 GPIO driver

### ISSUE THREAD

**Issue by SidineiSantosSousa** [dotnet/iot#2073] opened 2023-05-04 15:20 UTC
Is there any prediction of when the driver for the Orange Pi 5 will be available?

I thought the Orange Pi 5 was great and would like to use it with Dotnet IoT :(.

**Comment by krwq** [comment] 2023-05-04 15:36
[Triage] As soon as somebody contributes 😄 cc: @Ellerbach @ZhangGaoxing

**Comment by krwq** [comment] 2023-05-04 15:38
Closing as duplicate of https://github.com/dotnet/iot/issues/2066

**Closed by krwq** 2023-05-04 15:38 UTC
Labels: api-suggestion, Priority:3

**Comment by ZhangGaoxing** [comment] 2023-05-05 00:09
I currently do not have the board for RK3588s and it is slightly expensive😅
