### ISSUE TITLE
Error while waiting for pin interrupts

### ISSUE THREAD

**Issue by vulild** [dotnet/iot#1471] opened 2021-03-05 03:52 UTC
Unhandled exception. System.IO.IOException: Error while waiting for pin interrupts.
Mar 05 01:26:30 raspberrypi1 dotnet[6912]:    at System.Device.Gpio.Drivers.SysFsDriver.WasEventDetected(Int32 pollFileDescriptor, Int32 valueFileDescriptor, Int32& pinNumber, CancellationToken cancellationToken)
Mar 05 01:26:30 raspberrypi1 dotnet[6912]:    at System.Device.Gpio.Drivers.SysFsDriver.DetectEvents()
Mar 05 01:26:30 raspberrypi1 dotnet[6912]:    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
Mar 05 01:26:30 raspberrypi1 dotnet[6912]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 05 01:26:30 raspberrypi1 dotnet[6912]: --- End of stack trace from previous location where exception was thrown ---
Mar 05 01:26:30 raspberrypi1 dotnet[6912]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 05 01:26:30 raspberrypi1 dotnet[6912]:    at System.Threading.ThreadHelper.ThreadStart()

**Comment by pgrawehr** [comment] 2021-03-05 18:48
Probably a duplicate of #378. Does it always happen for you, or only intermittenly?

**Comment by Ellerbach** [comment] 2021-03-25 16:18
[Triage] I will go ahead and close this one as duplicate of #378. Please @vulild feel free to add anything new to the other issue. Thanks.

**Closed by Ellerbach** 2021-03-25 16:18 UTC
Labels: bug, untriaged

**Comment by vulild** [comment] 2021-03-29 05:10
安装了libgpiod-dev之后，不会报错了，但是程序会挂掉。建议把这个错误做成回调，或者屏蔽掉，我测试过屏蔽掉错误不会影响程序运行，也不影响引脚的监测。
